-- Name: tec_ecoreference; Type: TABLE;
--

CREATE TABLE public.tec_ecoreference (
    ec_ecid integer NOT NULL,
    ec_eco_code character varying(8) NOT NULL,
    ec_opening_name text NOT NULL
);

ALTER TABLE public.tec_ecoreference ALTER COLUMN ec_ecid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tec_ecoreference_ec_ecid_seq
    START WITH 3999
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tec_ecoreference
    ADD CONSTRAINT tec_ecoreference_ec_eco_code_ec_opening_name_key UNIQUE (ec_eco_code, ec_opening_name);

ALTER TABLE ONLY public.tec_ecoreference
    ADD CONSTRAINT tec_ecoreference_pkey PRIMARY KEY (ec_ecid);

CREATE INDEX idx_tec_code ON public.tec_ecoreference USING btree (ec_eco_code);

--
-- Name: teva_evaluations; Type: TABLE;
--

CREATE TABLE public.teva_evaluations (
    eva_evaid integer NOT NULL,
    eva_cp integer,
    eva_best_move text,
    eva_pos_id integer
);

ALTER TABLE public.teva_evaluations ALTER COLUMN eva_evaid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teva_evaluations_eva_evaid_seq
    START WITH 43129
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.teva_evaluations
    ADD CONSTRAINT teva_evaluations_eva_pos_id_key UNIQUE (eva_pos_id);

ALTER TABLE ONLY public.teva_evaluations
    ADD CONSTRAINT teva_evaluations_pkey PRIMARY KEY (eva_evaid);

CREATE INDEX idx_teva_pos_id ON public.teva_evaluations USING btree (eva_pos_id);

--
-- Name: tgam_game_positions; Type: TABLE;
--

CREATE TABLE public.tgam_game_positions (
    gam_gamid integer NOT NULL,
    gam_player text NOT NULL,
    gam_move_played text NOT NULL,
    gam_move_uci text,
    gam_resulting_pos_id integer,
    gam_move_num integer,
    gam_cp_change integer,
    gam_player_result character varying(5),
    gam_pos_id integer,
    gam_gdid integer
);

ALTER TABLE public.tgam_game_positions ALTER COLUMN gam_gamid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tgam_game_positions_gam_id_seq
    START WITH 1623595
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tgam_game_positions
    ADD CONSTRAINT tgam_game_positions_pkey PRIMARY KEY (gam_gamid);

ALTER TABLE ONLY public.tgam_game_positions
    ADD CONSTRAINT uq_tgam_game_pos_gdid UNIQUE (gam_gdid, gam_player, gam_pos_id);

CREATE INDEX idx_tgam_gdid ON public.tgam_game_positions USING btree (gam_gdid);

CREATE INDEX idx_tgam_player ON public.tgam_game_positions USING btree (gam_player);

CREATE INDEX idx_tgam_pos_id ON public.tgam_game_positions USING btree (gam_pos_id);

--
-- Name: tgd_gamesdecon; Type: TABLE;
-- Canonical source: nextjs-shared/src/chess/schema.sql — keep this block in sync with it.
--

CREATE TABLE public.tgd_gamesdecon (
    gd_gdid integer NOT NULL,
    gd_white_username character varying(64) NOT NULL,
    gd_black_username character varying(64) NOT NULL,
    gd_white_rating integer NOT NULL,
    gd_black_rating integer NOT NULL,
    gd_player character varying(64) NOT NULL,
    gd_player_color character varying(5) NOT NULL,
    gd_player_result character varying(8) NOT NULL,
    gd_opponent_username character varying(64) NOT NULL,
    gd_opponent_rating integer NOT NULL,
    gd_time_class character varying(16) NOT NULL,
    gd_time_control character varying(32),
    gd_is_rated boolean DEFAULT true NOT NULL,
    gd_termination character varying(64),
    gd_end_time integer NOT NULL,
    gd_eco_code character varying(8),
    gd_opening_name text,
    gd_game_url text,
    gd_opening_moves text,
    gd_pgn text,
    gd_chesscom_uuid character varying(64)
);

ALTER TABLE public.tgd_gamesdecon ALTER COLUMN gd_gdid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tgd_gamesdecon_gd_gdid_seq
    START WITH 73628
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tgd_gamesdecon
    ADD CONSTRAINT tgd_gamesdecon_pkey PRIMARY KEY (gd_gdid);

CREATE INDEX idx_tgd_eco ON public.tgd_gamesdecon USING btree (gd_eco_code);

CREATE INDEX idx_tgd_end_time ON public.tgd_gamesdecon USING btree (gd_end_time DESC);

CREATE INDEX idx_tgd_opponent ON public.tgd_gamesdecon USING btree (gd_opponent_username);

CREATE INDEX idx_tgd_player ON public.tgd_gamesdecon USING btree (gd_player);

CREATE INDEX idx_tgd_result ON public.tgd_gamesdecon USING btree (gd_player_result);

CREATE INDEX idx_tgd_time_class ON public.tgd_gamesdecon USING btree (gd_time_class);

--
-- Name: tgev_game_evals; Type: TABLE;
--

CREATE TABLE public.tgev_game_evals (
    gev_gevid integer NOT NULL,
    gev_chesscom_uuid character varying(64) NOT NULL,
    gev_player character varying(64) NOT NULL,
    gev_move_num smallint NOT NULL,
    gev_san text NOT NULL,
    gev_fen_before text NOT NULL,
    gev_fen_after text NOT NULL,
    gev_cp integer,
    gev_cp_before integer,
    gev_cp_loss integer,
    gev_best_move text,
    gev_best_move_san text,
    gev_best_line jsonb,
    gev_classification character varying(12),
    gev_depth smallint
);

ALTER TABLE public.tgev_game_evals ALTER COLUMN gev_gevid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tgev_game_evals_gev_gevid_seq
    START WITH 665
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tgev_game_evals
    ADD CONSTRAINT tgev_game_evals_gev_game_ref_gev_player_gev_move_num_key UNIQUE (gev_chesscom_uuid, gev_player, gev_move_num);

ALTER TABLE ONLY public.tgev_game_evals
    ADD CONSTRAINT tgev_game_evals_pkey PRIMARY KEY (gev_gevid);

CREATE INDEX idx_tgev_game ON public.tgev_game_evals USING btree (gev_chesscom_uuid);

CREATE INDEX idx_tgev_player ON public.tgev_game_evals USING btree (gev_player);

--
-- Name: tgr_gamesraw; Type: TABLE;
-- Canonical source: nextjs-shared/src/chess/schema.sql — keep this block in sync with it.
--

CREATE TABLE public.tgr_gamesraw (
    gr_player character varying(64) NOT NULL,
    gr_chesscom_uuid character varying(64) NOT NULL,
    gr_raw_data jsonb NOT NULL,
    gr_pgn text,
    gr_end_time integer NOT NULL,
    gr_time_class character varying(16)
);

ALTER TABLE ONLY public.tgr_gamesraw
    ADD CONSTRAINT tgr_gamesraw_pkey PRIMARY KEY (gr_chesscom_uuid, gr_player);

CREATE INDEX idx_tgr_end_time ON public.tgr_gamesraw USING btree (gr_end_time DESC);

CREATE INDEX idx_tgr_player ON public.tgr_gamesraw USING btree (gr_player);

--
-- Name: tpip_pipelinelog; Type: TABLE;
--

CREATE TABLE public.tpip_pipelinelog (
    pip_pipid integer NOT NULL,
    pip_step smallint NOT NULL,
    pip_step_name character varying(64) DEFAULT ''::character varying NOT NULL,
    pip_date_from date,
    pip_date_to date,
    pip_start integer DEFAULT 0 NOT NULL,
    pip_remaining integer DEFAULT 0 NOT NULL,
    pip_finish integer DEFAULT 0 NOT NULL,
    pip_attempted integer DEFAULT 0 NOT NULL,
    pip_processed integer DEFAULT 0 NOT NULL,
    pip_errors integer DEFAULT 0 NOT NULL,
    pip_skipped integer DEFAULT 0 NOT NULL,
    pip_duration_ms integer DEFAULT 0 NOT NULL
);

ALTER TABLE public.tpip_pipelinelog ALTER COLUMN pip_pipid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tpip_pipelinelog_pip_pipid_seq
    START WITH 53
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tpip_pipelinelog
    ADD CONSTRAINT tpip_pipelinelog_pkey PRIMARY KEY (pip_pipid);

--
-- Name: tpl_players; Type: TABLE;
--

CREATE TABLE public.tpl_players (
    pl_plid integer NOT NULL,
    pl_player character varying(64) NOT NULL,
    pl_avatar text,
    pl_display_name character varying(128),
    pl_rating_blitz integer,
    pl_last_synced_end_time integer
);

ALTER TABLE public.tpl_players ALTER COLUMN pl_plid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tpl_players_pl_plid_seq
    START WITH 3
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tpl_players
    ADD CONSTRAINT tpl_players_pkey PRIMARY KEY (pl_plid);

ALTER TABLE ONLY public.tpl_players
    ADD CONSTRAINT tpl_players_pl_username_key UNIQUE (pl_player);

--
-- Name: tplr_player_ratings; Type: TABLE;
--

CREATE TABLE public.tplr_player_ratings (
    plr_plrid integer NOT NULL,
    plr_player character varying(64) NOT NULL,
    plr_time_class character varying(16) NOT NULL,
    plr_rating integer NOT NULL
);

ALTER TABLE public.tplr_player_ratings ALTER COLUMN plr_plrid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tplr_player_ratings_plr_plrid_seq
    START WITH 5
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tplr_player_ratings
    ADD CONSTRAINT tplr_player_ratings_pkey PRIMARY KEY (plr_plrid);

ALTER TABLE ONLY public.tplr_player_ratings
    ADD CONSTRAINT tplr_player_ratings_plr_player_plr_time_class_key UNIQUE (plr_player, plr_time_class);

CREATE INDEX idx_tplr_player ON public.tplr_player_ratings USING btree (plr_player);

--
-- Name: tpos_positions; Type: TABLE;
--

CREATE TABLE public.tpos_positions (
    pos_id integer NOT NULL,
    pos_fen text NOT NULL,
    pos_reached integer DEFAULT 0,
    pos_color character(1),
    pos_ply_count integer,
    pos_move_num integer
);

ALTER TABLE public.tpos_positions ALTER COLUMN pos_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tpos_positions_pos_id_seq
    START WITH 1293037
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tpos_positions
    ADD CONSTRAINT tpos_positions_pkey PRIMARY KEY (pos_id);

ALTER TABLE ONLY public.tpos_positions
    ADD CONSTRAINT tpos_positions_pos_fen_key UNIQUE (pos_fen);

CREATE INDEX idx_tpos_reached ON public.tpos_positions USING btree (pos_reached DESC);

CREATE INDEX idx_tpos_move_num ON public.tpos_positions USING btree (pos_move_num);

--
-- Name: tqui_quiz; Type: TABLE;
--

CREATE TABLE public.tqui_quiz (
    qui_quiid integer NOT NULL,
    qui_session text NOT NULL,
    qui_pos_fen text NOT NULL,
    qui_move_played text,
    qui_correct boolean,
    qui_cp_change integer,
    qui_pos_id integer
);

ALTER TABLE public.tqui_quiz ALTER COLUMN qui_quiid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tqui_quiz_qui_quiid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tqui_quiz
    ADD CONSTRAINT tqui_quiz_pkey PRIMARY KEY (qui_quiid);

CREATE INDEX idx_tqui_session ON public.tqui_quiz USING btree (qui_session);

--
-- Name: tsa_savedanalyses; Type: TABLE;
--

CREATE TABLE public.tsa_savedanalyses (
    sa_said integer NOT NULL,
    sa_gdid integer,
    sa_save_type character varying(16) NOT NULL,
    sa_title character varying(256),
    sa_notes text,
    sa_line_pgn text,
    sa_line_moves jsonb,
    sa_starting_fen text,
    sa_starting_ply integer,
    sa_tree_data jsonb,
    sa_eco_code character varying(8),
    sa_opening_name text
);

ALTER TABLE public.tsa_savedanalyses ALTER COLUMN sa_said ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tsa_savedanalyses_sa_said_seq
    START WITH 2
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tsa_savedanalyses
    ADD CONSTRAINT tsa_savedanalyses_pkey PRIMARY KEY (sa_said);

CREATE INDEX idx_tsa_game ON public.tsa_savedanalyses USING btree (sa_gdid);

--
-- Name: xlg_logging; Type: TABLE;
--

CREATE TABLE public.xlg_logging (
    lg_lgid integer NOT NULL,
    lg_severity character(1),
    lg_caller character varying DEFAULT ''::character varying,
    lg_functionname character varying NOT NULL,
    lg_msg character varying NOT NULL,
    lg_datetime timestamp with time zone NOT NULL
);

ALTER TABLE public.xlg_logging ALTER COLUMN lg_lgid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.xlg_logging_lg_lgid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.xlg_logging
    ADD CONSTRAINT xlg_logging_pkey PRIMARY KEY (lg_lgid);
