-- Name: tec_ecoreference; Type: TABLE;
--

CREATE TABLE public.tec_ecoreference (
    ec_ecid integer NOT NULL,
    ec_eco_code character varying(8) NOT NULL,
    ec_opening_name text NOT NULL
);

ALTER TABLE public.tec_ecoreference ALTER COLUMN ec_ecid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tec_ecoreference_ec_ecid_seq
    START WITH 3999
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tec_ecoreference
    ADD CONSTRAINT tec_ecoreference_ec_eco_code_ec_opening_name_key UNIQUE (ec_eco_code, ec_opening_name);

ALTER TABLE ONLY public.tec_ecoreference
    ADD CONSTRAINT tec_ecoreference_pkey PRIMARY KEY (ec_ecid);

CREATE INDEX idx_tec_code ON public.tec_ecoreference USING btree (ec_eco_code);

--
-- Name: teva_evaluations; Type: TABLE;
--

CREATE TABLE public.teva_evaluations (
    eva_evaid integer CONSTRAINT teva_evaluations_eva_id_not_null NOT NULL,
    eva_cp integer,
    eva_best_move text,
    eva_pos_id integer,
    eva_depth smallint
);

ALTER TABLE public.teva_evaluations ALTER COLUMN eva_evaid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teva_evaluations_eva_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.teva_evaluations
    ADD CONSTRAINT teva_evaluations_eva_pos_id_key UNIQUE (eva_pos_id);

ALTER TABLE ONLY public.teva_evaluations
    ADD CONSTRAINT teva_evaluations_pkey PRIMARY KEY (eva_evaid);

CREATE INDEX idx_teva_pos_id ON public.teva_evaluations USING btree (eva_pos_id);

--
-- Name: tgam_game_positions; Type: TABLE;
--

CREATE TABLE public.tgam_game_positions (
    gam_gamid integer CONSTRAINT tgam_game_positions_gam_id_not_null NOT NULL,
    gam_move_played text NOT NULL,
    gam_move_uci text,
    gam_move_num integer,
    gam_cp_change integer,
    gam_pos_id integer,
    gam_gdid integer,
    gam_resulting_pos_id integer,
    gam_pos_fen text,
    gam_resulting_fen text
)
WITH (autovacuum_enabled='true');

ALTER TABLE public.tgam_game_positions ALTER COLUMN gam_gamid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tgam_game_positions_gam_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tgam_game_positions
    ADD CONSTRAINT tgam_game_positions_pkey PRIMARY KEY (gam_gamid);

CREATE INDEX idx_tgam_gdid ON public.tgam_game_positions USING btree (gam_gdid);

CREATE INDEX idx_tgam_pos_id ON public.tgam_game_positions USING btree (gam_pos_id);

CREATE INDEX idx_tgam_resulting_pos_id ON public.tgam_game_positions USING btree (gam_resulting_pos_id);


--
-- Name: tgd_gamesdecon; Type: TABLE;
-- Canonical source: nextjs-shared/src/chess/schema.sql — keep this block in sync with it.
--

CREATE TABLE public.tgd_gamesdecon (
    gd_gdid integer NOT NULL,
    gd_white_username character varying(64) NOT NULL,
    gd_black_username character varying(64) NOT NULL,
    gd_white_rating integer NOT NULL,
    gd_black_rating integer NOT NULL,
    gd_player character varying(64) NOT NULL,
    gd_player_color character varying(5) NOT NULL,
    gd_player_result character varying(8) NOT NULL,
    gd_opponent_username character varying(64) NOT NULL,
    gd_opponent_rating integer NOT NULL,
    gd_time_class character varying(16) NOT NULL,
    gd_time_control character varying(32),
    gd_is_rated boolean DEFAULT true NOT NULL,
    gd_termination character varying(64),
    gd_end_time integer NOT NULL,
    gd_eco_code character varying(8),
    gd_opening_name text,
    gd_game_url text,
    gd_opening_moves text,
    gd_pgn text,
    gd_chesscom_uuid character varying(64),
    gd_positions_purged boolean DEFAULT false NOT NULL,
    gd_final_eval integer
);

ALTER TABLE public.tgd_gamesdecon ALTER COLUMN gd_gdid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tgd_gamesdecon_gd_gdid_seq
    START WITH 73628
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tgd_gamesdecon
    ADD CONSTRAINT tgd_gamesdecon_pkey PRIMARY KEY (gd_gdid);

CREATE INDEX idx_tgd_eco ON public.tgd_gamesdecon USING btree (gd_eco_code);

CREATE INDEX idx_tgd_end_time ON public.tgd_gamesdecon USING btree (gd_end_time DESC);

CREATE INDEX idx_tgd_opponent ON public.tgd_gamesdecon USING btree (gd_opponent_username);

CREATE INDEX idx_tgd_player ON public.tgd_gamesdecon USING btree (gd_player);

CREATE INDEX idx_tgd_result ON public.tgd_gamesdecon USING btree (gd_player_result);

CREATE INDEX idx_tgd_time_class ON public.tgd_gamesdecon USING btree (gd_time_class);

--
-- Name: tgev_game_evals; Type: TABLE;
--

CREATE TABLE public.tgev_game_evals (
    gev_gevid integer NOT NULL,
    gev_gdid integer NOT NULL,
    gev_ply smallint CONSTRAINT tgev_game_evals_gev_move_num_not_null NOT NULL,
    gev_san text NOT NULL,
    gev_fen_after text NOT NULL,
    gev_cp integer,
    gev_best_move text,
    gev_best_move_san text,
    gev_best_line jsonb,
    gev_depth smallint,
    gev_cp_change integer
);

ALTER TABLE public.tgev_game_evals ALTER COLUMN gev_gevid ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE ONLY public.tgev_game_evals
    ADD CONSTRAINT tgev_game_evals_pkey PRIMARY KEY (gev_gevid);

ALTER TABLE ONLY public.tgev_game_evals
    ADD CONSTRAINT tgev_game_evals_gdid_move_num_key UNIQUE (gev_gdid, gev_ply);

CREATE INDEX idx_tgev_gdid ON public.tgev_game_evals USING btree (gev_gdid);

--
-- Name: tgr_gamesraw; Type: TABLE;
-- Canonical source: nextjs-shared/src/chess/schema.sql — keep this block in sync with it.
--

CREATE TABLE public.tgr_gamesraw (
    gr_player character varying(64) NOT NULL,
    gr_chesscom_uuid character varying(64) NOT NULL,
    gr_raw_data jsonb NOT NULL,
    gr_pgn text,
    gr_end_time integer NOT NULL,
    gr_time_class character varying(16)
);

ALTER TABLE ONLY public.tgr_gamesraw
    ADD CONSTRAINT tgr_gamesraw_pkey PRIMARY KEY (gr_chesscom_uuid, gr_player);

CREATE INDEX idx_tgr_end_time ON public.tgr_gamesraw USING btree (gr_end_time DESC);

CREATE INDEX idx_tgr_player ON public.tgr_gamesraw USING btree (gr_player);

--
-- Name: thab_habits; Type: TABLE;
--

CREATE TABLE public.thab_habits (
    hab_habid integer NOT NULL,
    hab_player character varying(64) NOT NULL,
    hab_pos_id integer NOT NULL,
    hab_move_san text NOT NULL,
    hab_move_uci text,
    hab_move_num integer,
    hab_move_times integer NOT NULL,
    hab_move_wins integer NOT NULL,
    hab_move_losses integer NOT NULL,
    hab_move_cp numeric(6,2),
    hab_dismissed boolean DEFAULT false NOT NULL,
    hab_resulting_pos_id integer,
    hab_opening_name text,
    hab_eco_code character varying(8),
    hab_last_occurred integer
);

ALTER TABLE public.thab_habits ALTER COLUMN hab_habid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.thab_habits_hab_habid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.thab_habits
    ADD CONSTRAINT thab_habits_pkey PRIMARY KEY (hab_habid);

ALTER TABLE ONLY public.thab_habits
    ADD CONSTRAINT thab_habits_hab_player_hab_pos_id_hab_move_san_key UNIQUE (hab_player, hab_pos_id, hab_move_san);

CREATE INDEX idx_thab_player ON public.thab_habits USING btree (hab_player);

--
-- Name: tmst_master_players; Type: TABLE;
--

CREATE TABLE public.tmst_master_players (
    mst_mstid integer NOT NULL,
    mst_first_name text,
    mst_last_name text NOT NULL,
    mst_fideid integer,
    mst_grade smallint,
    mst_priority boolean NOT NULL,
    mst_chesscom_handle text
);

ALTER TABLE public.tmst_master_players ALTER COLUMN mst_mstid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tmst_master_players_mst_mstid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tmst_master_players
    ADD CONSTRAINT tmst_master_players_pkey PRIMARY KEY (mst_mstid);

ALTER TABLE ONLY public.tmst_master_players
    ADD CONSTRAINT tmst_master_players_mst_fideid_key UNIQUE (mst_fideid);

CREATE INDEX idx_tmst_last_name ON public.tmst_master_players USING btree (mst_last_name);

--
-- Name: tfzp_fide_zip; Type: TABLE;
--

CREATE TABLE public.tfzp_fide_zip (
    fzp_data text NOT NULL
);

--
-- Name: tfxm_fide_xml; Type: TABLE;
--

CREATE TABLE public.tfxm_fide_xml (
    fxm_seq integer NOT NULL,
    fxm_data text NOT NULL
);

CREATE INDEX idx_tfxm_seq ON public.tfxm_fide_xml USING btree (fxm_seq);

--
-- Name: tfpl_fide_players; Type: TABLE;
--

CREATE TABLE public.tfpl_fide_players (
    fpl_fideid integer NOT NULL,
    fpl_first_name text,
    fpl_last_name text NOT NULL,
    fpl_rating smallint NOT NULL
);

CREATE INDEX idx_tfpl_fideid ON public.tfpl_fide_players USING btree (fpl_fideid);
CREATE INDEX idx_tfpl_rating ON public.tfpl_fide_players USING btree (fpl_rating);

--
-- Name: tpip_pipelinelog; Type: TABLE;
--

CREATE TABLE public.tpip_pipelinelog (
    pip_pipid integer NOT NULL,
    pip_run_id integer DEFAULT 0 NOT NULL,
    pip_pipeline_type character varying(16) NOT NULL,
    pip_step smallint NOT NULL,
    pip_sub_step character varying(1) NOT NULL,
    pip_step_name character varying(64) DEFAULT ''::character varying NOT NULL,
    pip_input_table character varying(64),
    pip_input_recs integer DEFAULT 0 NOT NULL,
    pip_output_table character varying(64),
    pip_output_recs integer DEFAULT 0 NOT NULL,
    pip_duration_ms integer DEFAULT 0 NOT NULL,
    pip_created timestamp DEFAULT now() NOT NULL
);

ALTER TABLE public.tpip_pipelinelog ALTER COLUMN pip_pipid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tpip_pipelinelog_pip_pipid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tpip_pipelinelog
    ADD CONSTRAINT tpip_pipelinelog_pkey PRIMARY KEY (pip_pipid);

--
-- Name: tpl_players; Type: TABLE;
--

CREATE TABLE public.tpl_players (
    pl_plid integer NOT NULL,
    pl_player character varying(64) NOT NULL,
    pl_avatar text,
    pl_display_name character varying(128),
    pl_last_synced_end_time integer
);

ALTER TABLE public.tpl_players ALTER COLUMN pl_plid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tpl_players_pl_plid_seq
    START WITH 3
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tpl_players
    ADD CONSTRAINT tpl_players_pkey PRIMARY KEY (pl_plid);

ALTER TABLE ONLY public.tpl_players
    ADD CONSTRAINT tpl_players_pl_username_key UNIQUE (pl_player);

--
-- Name: tplr_player_ratings; Type: TABLE;
--

CREATE TABLE public.tplr_player_ratings (
    plr_plrid integer NOT NULL,
    plr_player character varying(64) NOT NULL,
    plr_time_class character varying(16) NOT NULL,
    plr_rating integer NOT NULL
);

ALTER TABLE public.tplr_player_ratings ALTER COLUMN plr_plrid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tplr_player_ratings_plr_plrid_seq
    START WITH 5
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tplr_player_ratings
    ADD CONSTRAINT tplr_player_ratings_pkey PRIMARY KEY (plr_plrid);

ALTER TABLE ONLY public.tplr_player_ratings
    ADD CONSTRAINT tplr_player_ratings_plr_player_plr_time_class_key UNIQUE (plr_player, plr_time_class);

CREATE INDEX idx_tplr_player ON public.tplr_player_ratings USING btree (plr_player);

--
-- Name: tpos_positions; Type: TABLE;
--

CREATE TABLE public.tpos_positions (
    pos_id integer NOT NULL,
    pos_fen text NOT NULL,
    pos_reached integer DEFAULT 0,
    pos_color character(1),
    pos_move_num integer
);

ALTER TABLE public.tpos_positions ALTER COLUMN pos_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tpos_positions_pos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tpos_positions
    ADD CONSTRAINT tpos_positions_pkey PRIMARY KEY (pos_id);

ALTER TABLE ONLY public.tpos_positions
    ADD CONSTRAINT tpos_positions_pos_fen_key UNIQUE (pos_fen);

CREATE INDEX idx_tpos_move_num ON public.tpos_positions USING btree (pos_move_num);

CREATE INDEX idx_tpos_reached ON public.tpos_positions USING btree (pos_reached DESC);

--
-- Name: tpose_positions_eval; Type: TABLE;
--

CREATE TABLE public.tpose_positions_eval (
    pose_pos_id integer NOT NULL,
    pose_cp integer,
    pose_depth smallint,
    pose_best_move text
);

ALTER TABLE ONLY public.tpose_positions_eval
    ADD CONSTRAINT tpose_positions_eval_pkey PRIMARY KEY (pose_pos_id);

--
-- Name: tpur_workfile; Type: TABLE;
--

CREATE TABLE public.tpur_workfile (
    pur_pos_id integer NOT NULL,
    pur_pos_fen text NOT NULL,
    pur_pos_reached integer NOT NULL
);

CREATE INDEX idx_tpur_pos_id ON public.tpur_workfile USING btree (pur_pos_id);

--
-- Name: tqui_quiz; Type: TABLE;
--

CREATE TABLE public.tqui_quiz (
    qui_quiid integer NOT NULL,
    qui_session text NOT NULL,
    qui_pos_fen text NOT NULL,
    qui_move_played text,
    qui_correct boolean,
    qui_cp_change integer,
    qui_pos_id integer
);

ALTER TABLE public.tqui_quiz ALTER COLUMN qui_quiid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tqui_quiz_qui_quiid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tqui_quiz
    ADD CONSTRAINT tqui_quiz_pkey PRIMARY KEY (qui_quiid);

CREATE INDEX idx_tqui_session ON public.tqui_quiz USING btree (qui_session);

--
-- Name: xlg_logging; Type: TABLE;
--

CREATE TABLE public.xlg_logging (
    lg_lgid integer NOT NULL,
    lg_severity character(1),
    lg_level integer NOT NULL DEFAULT 1,
    lg_isupdate boolean NOT NULL DEFAULT false,
    lg_caller character varying DEFAULT ''::character varying,
    lg_functionname character varying NOT NULL,
    lg_table character varying DEFAULT ''::character varying,
    lg_msg character varying NOT NULL,
    lg_datetime timestamp with time zone NOT NULL
);

ALTER TABLE public.xlg_logging ALTER COLUMN lg_lgid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.xlg_logging_lg_lgid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.xlg_logging
    ADD CONSTRAINT xlg_logging_pkey PRIMARY KEY (lg_lgid);

--
-- Master games position database (secondary database — routed via xrtg_routing,
-- see .claude/CLAUDE.md and CONSUMING_PROJECTS.md §2a). Not present in the primary
-- database's schema at all — these tables physically live in local_chess_masters
-- (POSTGRES_URL1) / its production equivalent, listed here only because
-- scripts/schema.sql is the single source of truth for this project's full
-- structure across both databases.
--

--
-- Name: tmgr_mastergamesraw; Type: TABLE;
--

CREATE TABLE public.tmgr_mastergamesraw (
    mgr_player character varying(64) NOT NULL,
    mgr_chesscom_uuid character varying(64) NOT NULL,
    mgr_raw_data jsonb NOT NULL,
    mgr_pgn text,
    mgr_end_time integer NOT NULL,
    mgr_time_class character varying(16)
);

ALTER TABLE ONLY public.tmgr_mastergamesraw
    ADD CONSTRAINT tmgr_mastergamesraw_pkey PRIMARY KEY (mgr_chesscom_uuid, mgr_player);

CREATE INDEX idx_tmgr_end_time ON public.tmgr_mastergamesraw USING btree (mgr_end_time DESC);

CREATE INDEX idx_tmgr_player ON public.tmgr_mastergamesraw USING btree (mgr_player);

--
-- Name: tmgd_mastergamesdecon; Type: TABLE;
--

CREATE TABLE public.tmgd_mastergamesdecon (
    mgd_mgdid integer NOT NULL,
    mgd_white_username character varying(64) NOT NULL,
    mgd_black_username character varying(64) NOT NULL,
    mgd_white_rating integer NOT NULL,
    mgd_black_rating integer NOT NULL,
    mgd_player character varying(64) NOT NULL,
    mgd_player_color character varying(5) NOT NULL,
    mgd_player_result character varying(8) NOT NULL,
    mgd_opponent_username character varying(64) NOT NULL,
    mgd_opponent_rating integer NOT NULL,
    mgd_time_class character varying(16) NOT NULL,
    mgd_time_control character varying(32),
    mgd_is_rated boolean DEFAULT true NOT NULL,
    mgd_termination character varying(64),
    mgd_end_time integer NOT NULL,
    mgd_eco_code character varying(8),
    mgd_opening_name text,
    mgd_game_url text,
    mgd_opening_moves text,
    mgd_pgn text,
    mgd_chesscom_uuid character varying(64)
);

ALTER TABLE public.tmgd_mastergamesdecon ALTER COLUMN mgd_mgdid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tmgd_mastergamesdecon_mgd_mgdid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tmgd_mastergamesdecon
    ADD CONSTRAINT tmgd_mastergamesdecon_pkey PRIMARY KEY (mgd_mgdid);

CREATE INDEX idx_tmgd_eco ON public.tmgd_mastergamesdecon USING btree (mgd_eco_code);

CREATE INDEX idx_tmgd_end_time ON public.tmgd_mastergamesdecon USING btree (mgd_end_time DESC);

CREATE INDEX idx_tmgd_player ON public.tmgd_mastergamesdecon USING btree (mgd_player);

--
-- Name: tmps_masterpositions; Type: TABLE;
--

CREATE TABLE public.tmps_masterpositions (
    mps_id integer NOT NULL,
    mps_fen text NOT NULL,
    mps_reached integer DEFAULT 0,
    mps_color character(1),
    mps_move_num integer
);

ALTER TABLE public.tmps_masterpositions ALTER COLUMN mps_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tmps_masterpositions_mps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tmps_masterpositions
    ADD CONSTRAINT tmps_masterpositions_pkey PRIMARY KEY (mps_id);

ALTER TABLE ONLY public.tmps_masterpositions
    ADD CONSTRAINT tmps_masterpositions_mps_fen_key UNIQUE (mps_fen);

CREATE INDEX idx_tmps_reached ON public.tmps_masterpositions USING btree (mps_reached DESC);

--
-- Name: tmgp_mastergamepositions; Type: TABLE;
--

CREATE TABLE public.tmgp_mastergamepositions (
    mgp_mgpid integer NOT NULL,
    mgp_move_played text NOT NULL,
    mgp_move_uci text,
    mgp_move_num integer,
    mgp_pos_id integer,
    mgp_mgdid integer,
    mgp_resulting_pos_id integer,
    mgp_pos_fen text,
    mgp_resulting_fen text
);

ALTER TABLE public.tmgp_mastergamepositions ALTER COLUMN mgp_mgpid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tmgp_mastergamepositions_mgp_mgpid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tmgp_mastergamepositions
    ADD CONSTRAINT tmgp_mastergamepositions_pkey PRIMARY KEY (mgp_mgpid);

CREATE INDEX idx_tmgp_mgdid ON public.tmgp_mastergamepositions USING btree (mgp_mgdid);

CREATE INDEX idx_tmgp_pos_id ON public.tmgp_mastergamepositions USING btree (mgp_pos_id);

CREATE INDEX idx_tmgp_resulting_pos_id ON public.tmgp_mastergamepositions USING btree (mgp_resulting_pos_id);
